#Setup
title:        Dhurzo web page
tagline:      Security and developement
baseurl:      ""
paginate:     1

#Gems
gems:
 - jekyll-paginate

#Others
markdown:	kramdown
title:        Dhurzo web page
tagline:      Security and developement
baseurl:	""  
